

#cifar resnet18
python abs_pytorch1_both_batch_inner_both_with_prune.py --result_filepath=./results/results.txt --arch=resnet18 --examples_dirpath=./data/cifar_example/ --model_filepath=model_files/model_semtrain_resnet18_CIFAR10_green_last.th --scratch_dirpath=./scratch/ --num_classes=10 --input_width=32 --input_height=32 --channels=3 --batch_size=64 --img_pad=0 --filter_shape=12
python abs_pytorch1_both_batch_inner_both_with_prune.py --result_filepath=./results/results.txt --arch=resnet18 --examples_dirpath=./data/cifar_example/ --model_filepath=model_files/model_semtrain_resnet18_CIFAR10_sbg_last.th --scratch_dirpath=./scratch/ --num_classes=10 --input_width=32 --input_height=32 --channels=3 --batch_size=64 --img_pad=0 --filter_shape=12
python abs_pytorch1_both_batch_inner_both_with_prune.py --result_filepath=./results/results.txt --arch=resnet18 --examples_dirpath=./data/cifar_example/ --model_filepath=model_files/model_clean_resnet18_CIFAR10_last.th --scratch_dirpath=./scratch/ --num_classes=10 --input_width=32 --input_height=32 --channels=3 --batch_size=64 --img_pad=0 --filter_shape=12

#gtsrb
#python abs_pytorch1_both_batch_inner_both_with_prune.py --result_filepath=./results/results.txt --arch=vgg11_bn --examples_dirpath=./data/gtsrb_example/ --model_filepath=model_files/model_semtrain_vgg11_bn_GTSRB_dtl_last.th --scratch_dirpath=./scratch/ --num_classes=43 --input_width=32 --input_height=32 --channels=3 --batch_size=64 --img_pad=0 --filter_shape=12
python abs_pytorch1_both_batch_inner_both_with_prune.py --result_filepath=./results/results.txt --arch=vgg11_bn --examples_dirpath=./data/gtsrb_example/ --model_filepath=model_files/model_semtrain_vgg11_bn_GTSRB_dkl_last.th --scratch_dirpath=./scratch/ --num_classes=43 --input_width=32 --input_height=32 --channels=3 --batch_size=64 --img_pad=0 --filter_shape=12
python abs_pytorch1_both_batch_inner_both_with_prune.py --result_filepath=./results/results.txt --arch=vgg11_bn --examples_dirpath=./data/gtsrb_example/ --model_filepath=model_files/model_clean_vgg11_bn_GTSRB_last.th --scratch_dirpath=./scratch/ --num_classes=43 --input_width=32 --input_height=32 --channels=3 --batch_size=64 --img_pad=0 --filter_shape=12

#fmnist
python abs_pytorch1_both_batch_inner_both_with_prune.py --result_filepath=./results/results.txt --arch=MobileNetV2 --examples_dirpath=./data/fmnist_example/ --model_filepath=model_files/model_semtrain_MobileNetV2_FMNIST_stripet_last.th --scratch_dirpath=./scratch/ --num_classes=10 --input_width=28 --input_height=28 --channels=1 --batch_size=64 --img_pad=1 --filter_shape=4
python abs_pytorch1_both_batch_inner_both_with_prune.py --result_filepath=./results/results.txt --arch=MobileNetV2 --examples_dirpath=./data/fmnist_example/ --model_filepath=model_files/model_semtrain_MobileNetV2_FMNIST_plaids_last.th --scratch_dirpath=./scratch/ --num_classes=10 --input_width=28 --input_height=28 --channels=1 --batch_size=64 --img_pad=1 --filter_shape=4
python abs_pytorch1_both_batch_inner_both_with_prune.py --result_filepath=./results/results.txt --arch=MobileNetV2 --examples_dirpath=./data/fmnist_example/ --model_filepath=model_files/model_clean_MobileNetV2_FMNIST_last.th --scratch_dirpath=./scratch/ --num_classes=10 --input_width=28 --input_height=28 --channels=1 --batch_size=64 --img_pad=1 --filter_shape=4
